### PR TITLE
Issue 46

### LINKED ISSUE #46: Checkbox fields no longer export label value when raw_or_label equals true
Prior to 6.x setting the `raw_or_label` parameter to true would export checkbox field's labels as their value.

In 6.x setting `raw_or_label` to true simply changes the raw export value of checkbox fields from "0" to "Unchecked" and "1" to "Checked". 

To export records with checkbox values labeled as before one must pass `exportCheckboxLabel` and set the value to `true`. I'd like to propose potentially adding `checkbox_labels=False` as a keyword arg to `Project.export_records` to support this functionality. I'd be happy to start work if you think it would be a welcome addition.

### PR DESCRIPTION
**Pull request by tjrivera**
In REDCap >= 6.x it is necessary to include the exportCheckboxLabel parameter in the export records call in order to retrieve the labels for checkbox fields. Prior to 6.x this could be achieved simply by setting rawOrLabel to true. Its important to note that in order for checkbox labels to be exported as values you will still have to set raw_or_label to true in calls to export_records. Fixes #46.

### CODE REVIEW

**Comment by sburns** [comment]
@tjrivera from your perspective is this ready?

**Comment by tjrivera** [comment]
@sburns yes, I'm happy with it in its current state.

**Comment by sburns** [comment]
Thanks @tjrivera!

**Comment by alexanderkgonzalez** [comment]
Looking at the same issue..and who saves the day. @tjrivera  Thanks!

**Comment by sburns** [comment]
@alexanderkgonzalez can you install from master per the [docs](http://pycap.readthedocs.org/en/latest/), just want to make sure your systems can get back to working.

**Pull request merged**
